name: build

env:
  COLUMNS: 132

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: ./.github/actions/python-setup/
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          poetry run pip install "pytest-cov<2.6.0" codecov
          poetry run pip install -e ".[shellcode,dev,linux]"

      - name: Run unit tests
        run: poetry run python -m pytest --import-mode=append

